# This is a basic workflow that is manually triggered
name: learn-github-actions

# Controls when the action will run. Workflow runs when manually triggered using the UI or API.
on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  pull_request:
    branches: master
    types: opened

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test_commentary:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Workflow Webhook Action
      uses: distributhor/workflow-webhook@v1.0.5
      env:
        webhook_url: ${{ secrets.WEBHOOK_URL}}
        webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
